version: "3"
services:
  proxy:
    command: python services/main.py
    build:
      dockerfile: proxy/Dockerfile
      context: .
    volumes:
    - ./conf:/etc/nginx
    - .:/app
    ports:
    - 8000:80

  web:
    image:  jmalloc/echo-server
    depends_on:
      - proxy
    ports:
    - 8080:8080


  e2e:
    build:
      dockerfile: e2e/Dockerfile
      context: .
