version: "3"
services:
  proxy:
    command: python services/main.py
    build:
      dockerfile: proxy/Dockerfile
      context: .
    depends_on:
      - web
      - web2
    volumes:
    - ./conf:/etc/nginx
    - .:/app
    ports:
    - 8000:80

  web:
    image:  jmalloc/echo-server
    ports:
    - 8080:8080

  web2:
    image:  jmalloc/echo-server
    ports:
    - 8081:8080

  e2e:
    build:
      dockerfile: e2e/Dockerfile
      context: .

    depends_on:
      - proxy
